version: '3.8'

services:
  mysql-local:
    image: mysql:8.0
    container_name: bumbac-mysql-local
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: yarn_store_local
      MYSQL_USER: denis
      MYSQL_PASSWORD: local123
    ports:
      - "3307:3306"
    volumes:
      - mysql_local_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped

  adminer-local:
    image: adminer:latest
    container_name: bumbac-adminer-local
    ports:
      - "8082:8080"
    depends_on:
      - mysql-local
    restart: unless-stopped

  mailhog-local:
    image: mailhog/mailhog:latest
    container_name: bumbac-mailhog-local
    ports:
      - "1026:1025"
      - "8026:8025"
    restart: unless-stopped

volumes:
  mysql_local_data:
    driver: local