# 🔧 Development окружение - только вспомогательные сервисы
# MySQL локальная, Backend запускается через Maven (screen сессия)

services:
  mailhog:
    image: mailhog/mailhog:latest
    restart: unless-stopped
    ports:
      - "8045:8025"   # Web UI
      - "1025:1025"   # SMTP

  adminer:
    image: adminer:latest
    restart: unless-stopped
    ports:
      - "8091:8080"
    environment:
      ADMINER_DEFAULT_SERVER: mysql
