CREATE TABLE yarn_images (
    id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    yarn_id BIGINT NOT NULL,
    image_url VARCHAR(255) NOT NULL,
    alt_text VARCHAR(255),
    sort_order INT DEFAULT 0,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT fk_yarn_image FOREIGN KEY (yarn_id) REFERENCES yarns(id)
);
