server:
  port: 8082

# JWT Security
jwt:
  secret: ${JWT_SECRET}
  expiration: ${JWT_EXPIRATION:86400000}

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/yarn_store_staging
    username: denis
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false  # Отключено для staging
    properties:
      hibernate:
        format_sql: false

  mail:
    host: localhost
    port: 1025       # MailHog или тестовый SMTP
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: false
          starttls:
            enable: false

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  jackson:
    serialization:
      fail-on-empty-beans: false

  main:
    allow-bean-definition-overriding: true

# Swagger UI конфигурация для staging
springdoc:
  api-docs:
    path: /v3/api-docs   # JSON спецификация
  swagger-ui:
    operationsSorter: method
    tagsSorter: alpha
    display-request-duration: true
    try-it-out-enabled: true
  default-produces-media-type: application/json

# Actuator endpoints
management:
  endpoints:
    web:
      exposure:
        include:
          - health
          - info
          - prometheus
          - metrics
  endpoint:
    health:
      show-details: when_authorized  # Ограниченный доступ в staging

# Логирование
logging:
  level:
    com.bumbac: DEBUG
    org.springframework: INFO    # Менее подробное логирование для staging
    org.springframework.security: DEBUG
    org.hibernate.SQL: false     # Отключить SQL логи в staging