server:
  port: 8082

# JWT Security
jwt:
  secret: ${JWT_SECRET}
  expiration: ${JWT_EXPIRATION:86400000}

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/yarn_store_staging
    username: denis
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: false

  mail:
    host: smtp-relay.brevo.com
    port: 587
    username: ${BREVO_SMTP_USER}
    password: ${BREVO_SMTP_KEY}
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          ssl:
            trust: smtp-relay.brevo.com
            protocols: TLSv1.2
        from: ${MAIL_FROM}

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  jackson:
    serialization:
      fail-on-empty-beans: false
  main:
    allow-bean-definition-overriding: true

# Swagger UI конфигурация для staging
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
    tagsSorter: alpha
    display-request-duration: true
    try-it-out-enabled: true
  default-produces-media-type: application/json

# Actuator endpoints
management:
  endpoints:
    web:
      exposure:
        include:
          - health
          - info
          - prometheus
          - metrics
  endpoint:
    health:
      show-details: when_authorized

# Логирование
logging:
  level:
    com.bumbac: DEBUG
    org.springframework: INFO
    org.springframework.security: DEBUG
    org.hibernate.SQL: false

# CORS для staging фронтенда
cors:
  allowed-origins: https://staging-qscfgrt657.duckdns.org

# Настройки приложения
app:
  url:
    base: https://staging-qscfgrt657.duckdns.org
  mail:
    from: ${MAIL_FROM}
    reply-to: ""
