spring:
  profiles:
    include: mail                     # подключаем внешний файл настроек почты (application-mail.yml)
  messages:
    basename: i18n/messages          # путь к мультиязычным JSON-файлам

server:
  port: 8081                         # порт, на котором запускается backend

springdoc:
  swagger-ui:
    path: /swagger-ui.html          # путь к Swagger UI документации

logging:
  level:
    root: INFO                       # уровень логирования по умолчанию
    org.hibernate.SQL: DEBUG        # ↙ покажет SQL-запросы
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE  # ↙ покажет параметры запросов (bind variables)

management:                          # настройки Spring Actuator (например, /health)
  endpoints:
    web:
      exposure:
        include: health,info         # разрешаем доступ к health и info по HTTP

stripe:
  secret-key: ${STRIPE_SECRET}       # Stripe API ключ (берётся из .env)
  webhook-secret: ${STRIPE_WEBHOOK} # Stripe webhook-секрет (тоже из .env)
