server:
  port: ${SERVER_PORT}

spring:
  datasource:
    url: jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: ${JPA_DDL_AUTO}
    show-sql: ${JPA_SHOW_SQL:false}
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: ${JPA_FORMAT_SQL:false}

  mail:
    host: ${MAIL_HOST}
    port: ${MAIL_PORT}
    username: ${MAIL_USERNAME:}
    password: ${MAIL_PASSWORD:}
    protocol: ${MAIL_PROTOCOL:smtp}
    properties:
      mail:
        smtp:
          auth: ${MAIL_SMTP_AUTH:false}
          starttls:
            enable: ${MAIL_STARTTLS:false}

  flyway:
    enabled: ${FLYWAY_ENABLED:true}
    baseline-on-migrate: ${FLYWAY_BASELINE_ON_MIGRATE:true}
    baseline-version: ${FLYWAY_BASELINE_VERSION:1}

app:
  mail:
    from: ${MAIL_FROM}
  base-url: ${APP_URL_BASE}
  cors:
    allowed-origins: ${APP_URL_BASE}

  media:
    upload-dir: ${MEDIA_UPLOAD_DIR:/app/uploads/}
    base-url: ${MEDIA_BASE_URL}
    max-file-size: ${MEDIA_MAX_FILE_SIZE:20MB}
    allowed-formats: ${MEDIA_ALLOWED_FORMATS:jpg,jpeg,png,gif,webp}

  security:
    rate-limit:
      requests-per-minute: ${RATE_LIMIT_REQUESTS_PER_MINUTE:5}
      burst-capacity: ${RATE_LIMIT_BURST_CAPACITY:8}
      login-attempts-per-minute: ${RATE_LIMIT_LOGIN_ATTEMPTS_PER_MINUTE:5}
      login-burst-capacity: ${RATE_LIMIT_LOGIN_BURST_CAPACITY:8}

management:
  endpoints:
    web:
      exposure:
        include: ${MANAGEMENT_ENDPOINTS:health,info}
  endpoint:
    health:
      show-details: ${HEALTH_SHOW_DETAILS:when_authorized}

logging:
  level:
    com.bumbac: ${LOG_LEVEL_APP:DEBUG}
    org.springframework: ${LOG_LEVEL_SPRING:INFO}
    org.hibernate: ${LOG_LEVEL_HIBERNATE:WARN}
    org.springframework.security: ${LOG_LEVEL_SECURITY:DEBUG}
  file:
    name: ${LOG_FILE:logs/bumbac-staging.log}
  logback:
    rollingpolicy:
      max-file-size: ${LOG_MAX_FILE_SIZE:50MB}
      max-history: ${LOG_MAX_HISTORY:30}
      total-size-cap: ${LOG_TOTAL_SIZE_CAP:500MB}
