jwt:
  secret: ${JWT_SECRET}
  expiration: ${JWT_EXPIRATION:86400000}

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/yarn_store
    username: denis
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  cache:
    type: simple
    cache-names:
      - users
      - roles
      - carts
      - cartItems
      - colors
      - yarns
      - orders
      - payments
      - returns
      - shipments
      - favorites

  mail:
    host: smtp-relay.brevo.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  jackson:
    serialization:
      fail-on-empty-beans: false

  main:
    allow-bean-definition-overriding: true

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

# Конфигурация медиафайлов
app:
  media:
    upload-dir: ${MEDIA_UPLOAD_DIR:uploads/}
    base-url: ${MEDIA_BASE_URL:http://localhost:8080/media/}
    max-file-size: 10MB
    allowed-formats: jpg,jpeg,png,gif,webp

  # Конфигурация заказов
  order:
    default-status: NEW
    max-items-per-order: 100
    max-total-amount: 10000.00
    auto-clear-cart: true

  # Конфигурация безопасности и rate limiting
  security:
    rate-limit:
      requests-per-minute: ${RATE_LIMIT_REQUESTS_PER_MINUTE:3}
      burst-capacity: ${RATE_LIMIT_BURST_CAPACITY:5}
      login-attempts-per-minute: ${RATE_LIMIT_LOGIN_ATTEMPTS_PER_MINUTE:5}
      login-burst-capacity: ${RATE_LIMIT_LOGIN_BURST_CAPACITY:8}

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
    tagsSorter: alpha
    display-request-duration: true
    try-it-out-enabled: true
  default-produces-media-type: application/json

management:
  endpoints:
    web:
      exposure:
        include: [health, info, prometheus, metrics]
  endpoint:
    health:
      show-details: always

logging:
  level:
    root: INFO
    com.bumbac: DEBUG
    org.springframework.security: DEBUG
    org.springframework.web: DEBUG
  file:
    name: logs/bumbac-app.log
  pattern:
    file: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
    console: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
  logback:
    rollingpolicy:
      max-file-size: 10MB
      max-history: 30
      total-size-cap: 100MB
