spring:
  datasource:
    url: jdbc:mysql://192.168.0.20:3306/yarn_store?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: test
    password: MycVXR/7y.W]Hafj
    driver-class-name: com.mysql.cj.jdbc.Driver

    # HikariCP (по умолчанию в Boot) – тонкая настройка пула
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
      idle-timeout: 600000          # 10 мин
      pool-name: BumbacPool
      connection-timeout: 30000     # 30 сек

  jpa:
    open-in-view: false             # + производительность, – утечка сессий
    show-sql: false                 # SQL-лог в logging.level.hibernate.SQL
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
        highlight_sql: true
    hibernate:
      ddl-auto: validate            # ✔️  prod-режим: проверяем схему
      # dev-режим → update, но лучше Liquibase / Flyway

  flyway:
    baseline-on-migrate: true     # <--- добавлено для устранения ошибки
    enabled: true                 # можно указать явно
    locations: classpath:db/migration  # путь к миграциям (если используешь)

jwt:
  secret: ${JWT_SECRET:ChangeMeSuperSecretKeyWith32CharsMinimum}
  expiration: 86400000             # 24 h

warehouse:
  email: ${WAREHOUSE_EMAIL:orders@bumbac.md}

logging:
  level:
    root: INFO
    org.springframework.boot.context.config: DEBUG
    org.springframework.core.env: DEBUG
    org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration: DEBUG

