# Local development profile configuration
spring:
  # Импорт локальных переменных окружения (необязательный)
  config:
    import: optional:file:.env.local

  # Datasource configuration для LOCAL
  datasource:
    url: jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  # Flyway отключен для LOCAL
  flyway:
    enabled: true
    baseline-on-migrate: true
    baseline-version: 1
    baseline-description: "Init DB schema and seed"

    # JPA настройки для разработки
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  # Mail configuration для MailHog
  mail:
    host: ${MAIL_HOST}
    port: ${MAIL_PORT}
    username: ${MAIL_USERNAME:}
    password: ${MAIL_PASSWORD:}
    test-connection: false

# Server configuration для разработки
server:
  port: ${SERVER_PORT}
  address: ${SERVER_ADDRESS}
  error:
    include-message: always
    include-exception: true
    include-stacktrace: ${SERVER_ERROR_INCLUDE_STACKTRACE}
    include-binding-errors: always

# JWT configuration для LOCAL
jwt:
  secret: ${JWT_SECRET}
  expiration: ${JWT_EXPIRATION}

# Подробное логирование для разработки
logging:
  level:
    com.bumbac: DEBUG
    org.springframework.security: DEBUG
    org.springframework.web: DEBUG
    org.springframework.boot: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
  file:
    name: ${LOG_FILE:logs/yarn-local.log}

# CORS для фронтенда
cors:
  allowed-origins: http://localhost:3000,http://localhost:5173,http://127.0.0.1:3000,http://localhost:8080

# Application URLs
app:
  url:
    base: ${APP_URL_BASE}
  mail:
    from: ${MAIL_FROM}
    reply-to: ${MAIL_REPLY_TO}
  media:
    base-url: ${MEDIA_BASE_URL}

  # Security настройки для разработки
  security:
    rate-limit:
      requests-per-minute: 1000
      burst-capacity: 2000
      login-attempts-per-minute: 50
      login-burst-capacity: 100

# Management endpoints для разработки
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

# SpringDoc/Swagger для разработки
springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true