server:
  port: 8082

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/yarn_store_staging?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC&zeroDateTimeBehavior=convertToNull
    username: denis
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

  mail:
    host: localhost
    port: 1025
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: false
          starttls:
            enable: false

  flyway:
    enabled: false

app:
  mail:
    from: ${APP_MAIL_FROM:bumbac.staging@gmail.com}
  base-url: https://staging-qscfgrt657.duckdns.org
  cors:
    allowed-origins: https://staging-qscfgrt657.duckdns.org

management:
  endpoints:
    web:
      exposure:
        include:
          - health
          - info
  endpoint:
    health:
      show-details: when_authorized

logging:
  level:
    com.bumbac: DEBUG
    org.springframework: INFO
